{% set name = "spyrmsd" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee7b6c8c9535743f5499a1ebb1fc8244c6263499c5b9b4258727c024694fcb90

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - flit
  run:
    - python >=3.6
    - numpy
    - scipy
    - networkx >=2
    - qcelemental

test:
  imports:
    - spyrmsd

about:
  home: https://github.com/RMeli/spyrmsd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Symmetry-corrected RMSD

  description: |
    Symmetry-corrected RMSD
  doc_url: https://spyrmsd.readthedocs.io/en/master/
  dev_url: https://github.com/RMeli/spyrmsd

extra:
  recipe-maintainers:
    - RMeli
